spring.application.name=JournalApp
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017

#spring.data.mongodb.uri=mongodb+srv://kathanmodi2001_db_user:h6Avi8xFhtB55J8e@cluster0.j9alwv7.mongodb.net/journaldb?retryWrites=true&w=majority

spring.data.mongodb.database=journaldb

spring.data.mongodb.auto-index-creation=true