spring.application.name=JournalApp
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true

#spring.data.mongodb.uri=mongodb+srv://${MONGO_DB_ATLAS_USER}:${MONGO_DB_ATLAS_PASSWORD}@cluster0.j9alwv7.mongodb.net/journaldb?retryWrites=true&w=majority

spring.config.import=optional:file:.env[.properties]

weather_api_key=${WEATHER_API_KEY}